language: python
python:
  - "2.7"
services:
  - couchdb
before_install:
  - easy_install -U setuptools
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
  - pip install . --use-mirrors
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

before_script:
  - pip install -r test_requirements.txt --use-mirrors
script:
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_openprocurement.api_6d8c8aef9a_4
  - python -m properform Push 47.88.50.110:15554 asdf_openprocurement.api_6d8c8aef9a_4 ./profile_openprocurement.api_6d8c8aef9a_4



after_success:
  - coveralls
 #2017-08-13 20:37:51 modified at 0 #2017-08-13 20:37:56 modified at 1 #2017-08-13 20:38:01 modified at 2 #2017-08-13 20:38:05 modified at 3 #2017-08-13 20:38:10 modified at 4