language: python
python:
  - "2.7"
services:
  - couchdb
before_install:
  - easy_install -U setuptools
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq



install:
  - pip install . --use-mirrors
  - pip install http://op:x9W3jZ@dist.quintagroup.com/op/rfc6266-0.0.6.zip
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


before_script:
  - pip install -r test_requirements.txt --use-mirrors
script:
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_openprocurement.api_fa34a03f9c_4
  - python -m properform Push 47.88.50.110:15554 asdf_openprocurement.api_fa34a03f9c_4 ./profile_openprocurement.api_fa34a03f9c_4


after_success:
  - coveralls
 #2017-08-13 19:38:08 modified at 0 #2017-08-13 19:38:12 modified at 1 #2017-08-13 19:38:17 modified at 2 #2017-08-13 19:38:22 modified at 3 #2017-08-13 19:38:27 modified at 4