language: python

python:
  - "2.7"
services:
  - couchdb
cache:
  directories:
    - eggs
before_install:
  - pip install setuptools==7.0
  - python2 bootstrap.py
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
  - bin/buildout -N
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


script:
  - bin/nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_openprocurement.api_4f177ddd1f_2
  - python -m properform Push 47.88.50.110:15554 asdf_openprocurement.api_4f177ddd1f_2 ./profile_openprocurement.api_4f177ddd1f_2


after_success:
  - bin/coveralls
 #2017-08-13 19:15:53 modified at 0 #2017-08-13 19:15:57 modified at 1 #2017-08-13 19:16:02 modified at 2