language: python
python:
  - "2.7"
services:
  - couchdb
before_install:
  - easy_install -U setuptools
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - pip install . --use-mirrors
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

before_script:
  - pip install -r test_requirements.txt --use-mirrors
script:
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_openprocurement.api_30493ef227_3
  - python -m properform Push 47.88.50.110:15554 asdf_openprocurement.api_30493ef227_3 ./profile_openprocurement.api_30493ef227_3


after_success:
  - coveralls
 #2017-08-13 21:01:53 modified at 0 #2017-08-13 21:01:57 modified at 1 #2017-08-13 21:02:02 modified at 2 #2017-08-13 21:02:06 modified at 3