language: python

before_script:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get -qq update
  - sudo apt-get install libsodium13 -y
python:
  - "2.7"
services:
  - couchdb
env:
  global:
    - TZ=Europe/Kiev
  matrix:
    - SANDBOX_MODE=

cache:
  directories:
    - eggs
before_install:
  - pip install setuptools==7.0
  - python2 bootstrap.py
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
  - bin/buildout -N
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

script:
  - bin/nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_openprocurement.api_f5b57a2ab4_4
  - python -m properform Push 47.88.50.110:15554 asdf_openprocurement.api_f5b57a2ab4_4 ./profile_openprocurement.api_f5b57a2ab4_4

after_success:
  - bin/coveralls
 #2017-08-13 17:14:26 modified at 0 #2017-08-13 17:14:31 modified at 1 #2017-08-13 17:14:35 modified at 2 #2017-08-13 17:14:40 modified at 3 #2017-08-13 17:14:44 modified at 4