language: python

python:
  - "2.7"
services:
  - couchdb
cache:
  directories:
    - eggs
before_install:
  - pip install setuptools==7.0
  - python2 bootstrap.py
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
  - bin/buildout -N
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


script:
  - bin/nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_openprocurement.api_70d8801585_3
  - python -m properform Push 47.88.50.110:15554 asdf_openprocurement.api_70d8801585_3 ./profile_openprocurement.api_70d8801585_3


after_success:
  - bin/coveralls
 #2017-08-13 18:50:18 modified at 0 #2017-08-13 18:50:22 modified at 1 #2017-08-13 18:50:27 modified at 2 #2017-08-13 18:50:32 modified at 3