language: python
python:
  - "2.7"
services:
  - couchdb

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq



install:
  - pip install . --use-mirrors
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

before_script:
  - pip install -r test_requirements.txt --use-mirrors
script:
  - nosetests --with-coverage --cover-package=openprocurement.api --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_openprocurement.api_bc85fe88aa_2
  - python -m properform Push 47.88.50.110:15554 asdf_openprocurement.api_bc85fe88aa_2 ./profile_openprocurement.api_bc85fe88aa_2


after_success:
  - coveralls #2017-08-13 21:21:09 modified at 0 #2017-08-13 21:21:14 modified at 1 #2017-08-13 21:21:19 modified at 2